modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "fabricskyboxes"
version = "${version}"
displayName = "FabricSkyBoxes"
authors = "AMereBagatelle"
description = '''
Adds custom skybox support to MC
'''
#logoFile = ""

[[dependencies.fabricskyboxes]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fabricskyboxes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fabricskyboxes]]
modId = "architectury"
mandatory = true
versionRange = "[4.0.30,)"
ordering = "AFTER"
side = "BOTH"
    [dependencies.fabricskyboxes.custom.mc-publish]
    ignore=false
    curseforge="419699"
