name: Release CI
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run: ./gradlew build
      - name: Upload assets to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'fabric/build/libs/*-fabric.jar;forge/build/libs/*-forge.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Fabric to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          modrinth-id: YBz7DOs8
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 408209
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: fabric/build/libs/!(*-@(dev|sources)).jar

          version-type: release

          game-versions: 1.18.2

          loaders: fabric

          version-resolver: latest

          java: 17

          retry-attempts: 2
          retry-delay: 10000
